# Generated by Django 4.1.3 on 2022-11-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
                ('population', models.CharField(max_length=255)),
                ('official_website_url', models.CharField(max_length=255)),
                ('articles_count', models.CharField(max_length=255)),
                ('admin_docs_count', models.CharField(max_length=255)),
                ('impacters_count', models.CharField(max_length=255)),
                ('websites_count', models.CharField(max_length=255)),
                ('sources_count', models.CharField(max_length=255)),
            ],
        ),
    ]
